name: page_transition
description: Flutter Page Transition Package which is the transition second page
version: 1.1.4
author: Yasin ilhan<yasinilhan61@gmail.com>
homepage: https://github.com/kalismeras61/flutter_page_transition

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_web: any

dev_dependencies:
  flutter_web_test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
